### ISSUE TITLE
[Bug]: cuDNN_STATUS_NOT_SUPPORTED with Non-Contiguous Input During MP3 Processing in Applio

### ISSUE THREAD

**Issue by SnabbSpelare** [IAHispano/Applio#955]
### Project Version

3.2.8

### Platform and OS Version

Windows 11 64-bit, Chrome

### Affected Devices

Windows

### What happened?

Successfully installed and running and trained a model but then after trying to use the **Inference** feature with my own trained voice model within Applio it decided to throw me multiple errors. One for unsupported format which was "m4a" I even reopened the program but not changing the error. I hope I am being clear enough. Would love for this to work, it's an amazing looking interface with a lot of potential! Thanks in advance!

```
INFO: Could not find files for the given pattern(s).
* Running on local URL:  http://127.0.0.1:6969

To create a public link, set `share=True` in `launch()`.
Converting audio 'assets\audios\minecraftvideofromyoutube.mp3'...
An error occurred during audio conversion: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
Traceback (most recent call last):
  File "C:\Users\Snbb\Desktop\Applio\rvc\infer\infer.py", line 296, in convert_audio
    audio_opt = self.vc.pipeline(
  File "C:\Users\Snbb\Desktop\Applio\rvc\infer\pipeline.py", line 601, in pipeline
    pitch, pitchf = self.get_f0(
  File "C:\Users\Snbb\Desktop\Applio\rvc\infer\pipeline.py", line 359, in get_f0
    f0 = self.model_rmvpe.infer_from_audio(x, thred=0.03)
  File "C:\Users\Snbb\Desktop\Applio\rvc\lib\predictors\RMVPE.py", line 503, in infer_from_audio
    hidden = self.mel2hidden(mel)
  File "C:\Users\Snbb\Desktop\Applio\rvc\lib\predictors\RMVPE.py", line 477, in mel2hidden
    hidden = self.model(mel)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\rvc\lib\predictors\RMVPE.py", line 347, in forward
    x = self.fc(x)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\rvc\lib\predictors\RMVPE.py", line 560, in forward
    return self.gru(x)[0]
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Snbb\Desktop\Applio\env\lib\site-packages\torch\nn\modules\rnn.py", line 1133, in forward
    result = _VF.gru(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.
```

### Steps to reproduce

1. Run the applio
2. agree to terms of use
3. then clcik convert
4. ..here..we..are...

### Expected behavior

To get a completely voice over by another voice.

### Attachments

![Image](https://github.com/user-attachments/assets/a64f882a-b796-4cd4-b90e-53521d25fe40)

**Comment by AznamirWoW** [comment]
how big is the file you're trying to convert?

**Comment by blaisewf** [comment]
try with split audio

**Comment by SnabbSpelare** [comment]
It was just a YouTube video so it couldn't have been big. I'll split it and see if anything changes.

**Comment by SnabbSpelare** [comment]
It's working now! Thank you all for giving me your tips. For the record I didn't try the same audio but I used a few short samples and it works! thanks.
